src/index/pre_processor.rs
src/index/tests.rs
tests/correctness/arrays.rs
tests/tests.rs

testing correct writing to array for up to 3 dimensions

fix for #97 - missing correctness-tests for arrays

---

src/codegen/mod.rs
src/codegen/tests/mod.rs
src/index/pre_processor.rs
src/index/visitor.rs
src/parser/tests.rs
tests/correctness/custom_datatypes.rs
tests/correctness/global_variables.rs
tests/tests.rs

Fixes #77 
Add tests for various datatype usecases and fix enum initialization issues.

Add Enum and Struct tests

---

src/index/tests.rs

Tests that an Array defined inside a struct gets its own datatype.

Add preprocessing test for arrays nested in structs

---

src/codegen/mod.rs
src/codegen/tests/mod.rs
src/codegen/tests/typesystem.rs
src/codegen/typesystem.rs
tests/correctness/datatypes.rs

Fixed some float conversion issues and added tests for float access
Fixed float return type support
Fixes #106

Added float tests and support for returns

---

src/ast.rs
src/codegen/mod.rs
src/codegen/tests/codegen_error_messages.rs
src/codegen/tests/mod.rs
src/parser/control/tests.rs
src/parser/expressions/mod.rs
src/parser/expressions/tests.rs
src/parser/mod.rs
src/parser/tests.rs

i created an extra issue for the bad error-message for the generated-array type (see #118 )

Riederm/fix #117

---

src/codegen/mod.rs
src/codegen/tests/codegen_error_messages.rs

make sure errors inside array access (e.g. myArray[x + 5]) work
correclty

fix #113 error reporting inside array-access

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
docker-build/Dockerfile
docker-build/action.yml
src/codegen/tests/code_gen_tests.rs
src/codegen/tests/typesystem_test.rs

Fixed the tests for llvm 11, and moved the docker and action files to
support LLVM11
Fixes #87

Support LLVM 11

---

src/ast.rs
src/codegen/generators/data_type_generator.rs
src/codegen/generators/expression_generator.rs
src/codegen/generators/statement_generator.rs
src/codegen/generators/struct_generator.rs
src/codegen/generators/variable_generator.rs
src/codegen/tests/code_gen_tests.rs
src/index.rs
src/index/pre_processor.rs
src/index/tests/index_tests.rs
src/index/visitor.rs
src/parser.rs
src/parser/expressions_parser.rs
src/parser/tests/parser_tests.rs
tests/correctness/initial_values.rs

so far only 1-dimensional arrays work 
maybe i can work on multi-dimensional arrays tomorrow :-/

Array initializer

---

src/codegen/generators/expression_generator.rs
src/codegen/tests/code_gen_tests.rs

Add support for qualified function calls

---

Cargo.lock
Cargo.toml
src/cli.rs
src/cli_tests.rs
src/lib.rs
src/main.rs

moved to structopt-library for cli parameter handling

rustyc cli parameter handling

---

README.md
src/ast.rs
src/codegen.rs
src/codegen/generators/expression_generator.rs
src/codegen/generators/pou_generator.rs
src/codegen/generators/statement_generator.rs
src/codegen/llvm_typesystem.rs
src/codegen/tests/code_gen_tests.rs
src/codegen/tests/typesystem_test.rs
src/index.rs
src/index/tests/index_tests.rs
src/index/visitor.rs
src/lexer.rs
src/lexer/tests/lexer_tests.rs
src/parser.rs
src/parser/tests/parser_tests.rs
tests/correctness/custom_datatypes.rs
tests/correctness/datatypes.rs

Added support for actions
Fixes #138

Actions Support

---

README.md
src/ast.rs
src/codegen/generators/data_type_generator.rs
src/codegen/generators/expression_generator.rs
src/codegen/generators/statement_generator.rs
src/codegen/tests/code_gen_tests.rs
src/index/visitor.rs
src/lexer.rs
src/lexer/tests/lexer_tests.rs
src/lib.rs
src/main.rs
src/parser.rs
src/parser/tests/parser_tests.rs
src/typesystem.rs
tests/correctness/functions.rs

Support var in out #162

---

book/src/SUMMARY.md
book/src/libraries.md
book/src/libraries/external_functions.md
book/src/using_rusty.md
src/ast.rs
src/ast/pre_processor.rs
src/codegen/generators/expression_generator.rs
src/codegen/generators/pou_generator.rs
src/codegen/tests/code_gen_tests.rs
src/index.rs
src/index/tests/index_tests.rs
src/index/visitor.rs
src/lexer.rs
src/lexer/tests/lexer_tests.rs
src/main.rs
src/parser.rs
src/parser/tests/parser_tests.rs
src/typesystem.rs

Add varargs support to functions
Fixes #112

Varargs support

---

book/custom.js
book/iecst.min.js
book/src/intro_1.md
book/src/libraries/external_functions.md

use [Highlightjs Structured Text language support IEC 61131-3](https://github.com/highlightjs/highlightjs-structured-text) to add ST syntax highlighting support to the book

Add Syntax highlighting to ST

---

.github/workflows/rust.yml
src/codegen/generators/pou_generator.rs

Add support for code coverage using tarpaulin and codecov.

Add Code Coverage

---

src/codegen/tests/code_gen_tests.rs
src/typesystem.rs

added alias types for
- D --> DATE
- T --> TIME
- TOD --> TIME_OF_DAY
- DT --> DATE_AND_TIME

support short type-names for dates and times

---

src/ast/pre_processor.rs
src/lib.rs
src/parser.rs
src/parser/tests/expressions_parser_tests.rs
src/parser/tests/parse_errors/parse_error_classes_tests.rs
src/parser/tests/parse_errors/parse_error_containers_tests.rs

Parse the function's return type as a normal type

---

src/codegen/tests/code_gen_tests.rs

test-case for #274
this test-case was solved by #208, no changes required

added test case for const-expr in dt-declarations

---

src/codegen/generators/expression_generator.rs
src/codegen/tests/expression_tests.rs
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__unary_expressions_can_be_real.snap
src/resolver.rs
src/resolver/tests/resolve_expressions_tests.rs
src/typesystem.rs
tests/correctness/expressions.rs
tests/tests.rs

Make sure negations work on REAL

---

src/ast/pre_processor.rs
src/cli.rs
src/codegen/generators/data_type_generator.rs
src/codegen/generators/expression_generator.rs
src/codegen/generators/llvm.rs
src/codegen/generators/pou_generator.rs
src/codegen/generators/statement_generator.rs
src/codegen/llvm_typesystem.rs
src/compile_error.rs
src/index.rs
src/index/visitor.rs
src/lexer.rs
src/lib.rs
src/main.rs
src/parser/expressions_parser.rs
src/resolver.rs
src/resolver/const_evaluator.rs
src/typesystem.rs

- refactored .unwrap() calls where possible
- introduced Results where appropriate
- replaced Result.unwrap() with ? where possible
- replaced .unwrap() with .expect(...) to reflect that this is a conscious panic
closes #261

Issue 261 refactor the indexer so it does not crash on errors

---

src/codegen/generators/statement_generator.rs
src/codegen/tests/snapshots/rusty__codegen__tests__directaccess_test__bitaccess_assignment.snap
src/codegen/tests/snapshots/rusty__codegen__tests__directaccess_test__byteaccess_assignment.snap
src/codegen/tests/snapshots/rusty__codegen__tests__directaccess_test__chained_bit_assignment.snap
src/codegen/tests/snapshots/rusty__codegen__tests__directaccess_test__dwordaccess_assignment.snap
src/codegen/tests/snapshots/rusty__codegen__tests__directaccess_test__qualified_reference_assignment.snap
src/codegen/tests/snapshots/rusty__codegen__tests__directaccess_test__wordaccess_assignment.snap
tests/correctness/bitaccess.rs

Bitaccess assignment should not override old values

---

src/ast.rs
src/ast/pre_processor.rs
src/codegen/generators/pou_generator.rs
src/codegen/tests/code_gen_tests.rs
src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__default_values_for_not_initialized_function_vars.snap
src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__function_with_local_temp_var_initialization.snap
src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__function_with_local_var_initialization_and_call.snap
src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__pointer_and_array_access_to_in_out.snap
src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__program_with_local_temp_var_initialization.snap
src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__variable_with_same_name_as_data_type.snap
src/codegen/tests/snapshots/rusty__codegen__tests__directaccess_test__bitaccess_assignment.snap
src/codegen/tests/snapshots/rusty__codegen__tests__directaccess_test__qualified_reference_assignment.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__aliased_number_type_comparing_test.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__aliased_ranged_number_type_comparing_test.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__cast_lword_to_pointer.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__cast_pointer_to_lword.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__ranged_number_type_comparing_test.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__string_comparison_test.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__string_equal_with_constant_test.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__string_greater_or_equal_with_constant_test.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__string_greater_with_constant_test.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__string_less_with_constant_test.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__string_not_equal_with_constant_test.snap
src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__string_smaller_or_equal_with_constant_test.snap
src/parser.rs
src/resolver/const_evaluator.rs
tests/correctness/control_flow.rs
tests/correctness/functions.rs
tests/correctness/initial_values.rs

Issue 396 uninitialized function values are not 0

---

.devcontainer/Dockerfile
.github/workflows/doc.yml
.github/workflows/rust.yml
scripts/build.sh
src/ast/pre_processor.rs
src/typesystem.rs

I updated the images in the build to use the :latest instead of a fix version
The dev container is also updated.
Rust version on windows is also bumped to 1.60.0

Use the new coverage flag, update image

---

.devcontainer/Dockerfile
.gitpod.yml

Update the dev container to install git.
This makes it possible to work with gitpod.
Also configured the gitpod prebuild features.

Update Devcontainer and Gitpod config

---

tests/correctness/functions.rs

Hi,
I ran into some problems/bugs while playing with the compiler.  Really cool project, by the way :)
In particular, there were two issues that I identified and I've built reproducer testcases for each. I believe the problems both originate from `VAR_OUTPUT`s getting lowered into a reference (#530).
One test checks behavior when an output is used inside the function-block, but not assigned in the call.  The other tests whether outputs are persisted properly across invocations.
As the tests are of course failing right now, I assume you probably want them annotated with `#[ignore = "..."]`, similar to some other ones I saw?

Add two tests related to VAR_OUTPUT

---

README.md

switch to official github badge

fix build-status badge in readme.md

---

Cargo.lock
Cargo.toml
tests/integration/build_description_tests.rs
tests/tests.rs

Not sure if this is enough or if we should do this for all integration tests

Make the build descriptions tests run in serial

---

book/src/datatypes.md
tests/correctness/methods.rs

testcase added, unrelated typo fix in doc

Methods cannot resolve non class functions (#402)

---

src/ast.rs
src/codegen/tests/directaccess_test.rs
src/codegen/tests/snapshots/rusty__codegen__tests__directaccess_test__lwordaccess_assignment.snap
src/lexer.rs
src/lexer/tests/lexer_tests.rs
src/lexer/tokens.rs
src/resolver.rs
src/resolver/tests/resolve_expressions_tests.rs
tests/integration/command_line_compile.rs
tests/integration/data/io.st
tests/integration/snapshots/tests__integration__command_line_compile__hardware_conf_full_pass_json.snap
tests/integration/snapshots/tests__integration__command_line_compile__hardware_conf_full_pass_toml.snap

test for hardware conf, problem with LWORD size hardware access, fix coming in next commit

test added for Hardware access LWORD not supported (#676)

---

src/codegen/generators/expression_generator.rs
src/codegen/llvm_typesystem.rs
src/codegen/tests/function_tests.rs
src/codegen/tests/snapshots/rusty__codegen__tests__function_tests__autocast_argument_literals_for_function_call.snap
src/codegen/tests/snapshots/rusty__codegen__tests__function_tests__bitcast_argument_references_for_function_call.snap
src/codegen/tests/snapshots/rusty__codegen__tests__function_tests__passing_arguments_to_functions_by_ref_and_val.snap

Fixes https://github.com/PLC-lang/rusty/issues/698

Fix IR for `passing_arguments_to_functions_by_ref_and_val`

---

src/validation.rs
src/validation/tests/statement_validation_tests.rs

Allow array access when validating if an argument can be passed by ref

---

.devcontainer/Dockerfile

installs git in the devcontainer's docker image

make gitpod work again

---

src/index/tests/index_tests.rs
src/parser.rs
src/validation/tests/assignment_validation_tests.rs
src/validation/tests/snapshots/rusty__validation__tests__assignment_validation_tests__string_type_alias_assignment_can_be_validated.snap

Fix parsing of string-type aliases without explicit size

---

xtask/src/main.rs
xtask/src/reporter.rs
xtask/src/reporter/sysout.rs
xtask/src/task.rs
xtask/src/task/compile.rs
xtask/src/task/lexer.rs
xtask/src/task/run.rs

Commit https://github.com/PLC-lang/rusty/commit/d958e40e734e182afbf359609a1483028d329013 introduced a issue with the JSON schema being different than it was before, see <https://github.com/PLC-lang/rusty/blob/dad6598c1cd2884d4c06b28af82ecbee40bea282/metrics.json#L46-L47>
This PR fixes this such that the previous schema is restored.

Fix Metrics Serialization Issue

---

libs/stdlib/src/bistable_functionblocks.rs
libs/stdlib/src/counters.rs

There were a couple of unnecessary unsafe blocks that I chose to remove, so
nobody has to wonder why they are there.

Remove unnecessary unsafe blocks

---

compiler/plc_driver/src/cli.rs
compiler/plc_driver/src/lib.rs
compiler/plc_project/src/build_config.rs

The PLC Json schema is now part of the source.
It can be printed using plc config schema

feat: embed the plc json schema into the source

---

compiler/plc_diagnostics/src/diagnostics.rs
compiler/plc_driver/src/cli.rs
compiler/plc_driver/src/lib.rs
compiler/plc_xml/src/model/interface.rs
compiler/plc_xml/src/xml_parser/control.rs
compiler/plc_xml/src/xml_parser/tests.rs
libs/stdlib/src/date_time_extra_functions.rs
src/builtins.rs
src/codegen/debug.rs
src/codegen/generators/expression_generator.rs
src/codegen/generators/statement_generator.rs
src/index.rs
src/index/symbol.rs
src/index/tests/index_tests.rs
src/resolver.rs
src/resolver/const_evaluator.rs
src/validation/variable.rs
tests/correctness/bitaccess.rs

Updating clippy and format in preparation for https://github.com/PLC-lang/rust-llvm-images/pull/12

ci: run clippy with rust 1.75

---

.vscode/launch.json

Prints any log calls in VSCodes debug console

chore: Enable logging in VSCode debug view

---

src/parser.rs
src/parser/tests/class_parser_tests.rs
src/parser/tests/parse_errors/parse_error_classes_tests.rs

Also adds a few additional parser-tests in regards to methods.

feat: add parse-error for methods outside of supported POUs

---

src/validation/tests/duplicates_validation_test.rs

Adds a validation test to verify that duplicate method names within the same POU return errors.

tests: Add duplicate symbol tests for method names

---

book/src/arch/linker.md

Fix markdown typos.

---

book/src/build_and_install.md

just build requirement instructions update

docs: update build doc for ubuntu
