src/ast.rs, src/lexer/mod.rs, src/parser/control/mod.rs, src/parser/mod.rs, src/parser/tests.rs
including line-number, offset of the problem and the
text that actually caused the problem. 
e.g.
```expected KeywordEndVar, but found 'END_PROGRAM' [KeywordEndProgram] at line: 1 offset: 16..27```
=> added basic parsing error reporting

src/codegen.rs, src/codegen/tests/code_gen_tests.rs, tests/correctness/initial_values.rs
generate an assignment statement inside the function for every VAR
with an initializer
Fixes #125
=> Initial values for functions

src/codegen.rs, src/codegen/generators/pou_generator.rs, src/codegen/tests/code_gen_tests.rs, tests/correctness/functions.rs
Split the generation of POUs
Allow the POUs to all be indexed before they get generated
This allows POUs to be called out of order
Fixes #111
=> Bugfix #111 functions out of order

src/lexer.rs, src/lexer/tests/lexer_tests.rs
\r is now correctly ignored by the lexer.
It seems that \n is already ignored, but it is now covered in the test.
=> Ignore Carriage return when lexing (Windows Support)

.devcontainer/Dockerfile, README.md, src/codegen.rs, src/codegen/generators/data_type_generator.rs, src/codegen/generators/expression_generator.rs, src/codegen/generators/pou_generator.rs, src/codegen/generators/struct_generator.rs, src/codegen/tests/code_gen_tests.rs, src/index.rs, src/parser/tests/parser_tests.rs, tests/correctness/initial_values.rs
struct instance variables can be statically initialized,
all fields must be set
whats still missing is:
- use initial values defined on the struct's type declaration if the value is not provided in the instance initialization
=> add support for struct instance initialization (fix #131)

README.md, src/ast.rs, src/codegen/generators/data_type_generator.rs, src/codegen/generators/llvm.rs, src/codegen/generators/pou_generator.rs, src/codegen/generators/statement_generator.rs, src/codegen/generators/struct_generator.rs, src/codegen/llvm_index.rs, src/codegen/tests/code_gen_tests.rs, src/index.rs, src/index/tests/index_tests.rs, src/index/visitor.rs, src/lexer.rs, src/parser.rs, src/parser/control_parser.rs, src/parser/tests.rs, src/parser/tests/control_parser_tests.rs, src/parser/tests/expressions_parser_tests.rs, src/parser/tests/parser_tests.rs, src/typesystem.rs, tests/correctness/datatypes.rs, tests/correctness/sub_range_types.rs, tests/tests.rs
_ calls apropriate sub-range check function
_ chooses the appropriate check function based on the
variables datatype.
_ added unit & correctness tests
apply format to enable rebase
fixes #150
=> parse support & codegen for subRangeType

.devcontainer/Dockerfile
also dont run rustup, and cargo install as root so we dont
build a cargo-cache that is owned by root
=> updated docker file to rust:latest, install vim

src/codegen/generators/expression_generator.rs, src/codegen/generators/llvm.rs, src/codegen/generators/pou_generator.rs, src/lib.rs, src/parser.rs, src/parser/control_parser.rs, src/parser/expressions_parser.rs
Errors should be propagated to main
This commits makes sure the parser does not panic .
Some LLVM and Codegen functions were also still panicing/unwrapping.
=> Remove panics and unwraps from parser and LLVM

src/ast.rs, src/codegen/generators/expression_generator.rs, src/codegen/generators/llvm.rs, src/codegen/generators/pou_generator.rs, src/codegen/generators/statement_generator.rs, src/codegen/llvm_index.rs, src/codegen/llvm_typesystem.rs, src/codegen/tests.rs, src/codegen/tests/code_gen_tests.rs, src/codegen/tests/codegen_error_messages_tests.rs, src/compile_error.rs, src/index.rs, src/index/tests/index_tests.rs, src/index/visitor.rs, src/lexer.rs, src/lexer/tests/lexer_tests.rs, src/lib.rs, src/main.rs, src/parser.rs, src/parser/control_parser.rs, src/parser/expressions_parser.rs, src/parser/tests.rs, src/parser/tests/control_parser_tests.rs, src/parser/tests/expressions_parser_tests.rs, src/parser/tests/parser_tests.rs, tests/correctness/external_functions.rs, tests/tests.rs
Preparation for multi file support
The SourceRange in the AST now also contains a file path.
If the file path is not specified (mostly tests or undefined scenarios) we use an empty one for now.
=> Make the AST hold a file location

Cargo.lock, Cargo.toml, book/src/using_rusty.md, src/ast.rs, src/cli.rs, src/codegen/generators/expression_generator.rs, src/codegen/tests/code_gen_tests.rs, src/compile_error.rs, src/index.rs, src/lexer/tests/lexer_tests.rs, src/lib.rs, src/main.rs, src/parser.rs, tests/correctness/custom_datatypes.rs, tests/correctness/external_functions.rs, tests/tests.rs
_ the cli now accepts mulitple input-files in the end.
e.g. rustyc --ir file1.st file2.st
_ the cli now accepts glob expressions
e.g. ./**/*.st
fixes #91
=> allow mulitple files in compilation

book/src/datatypes.md, src/ast.rs, src/codegen/generators/data_type_generator.rs, src/codegen/generators/expression_generator.rs, src/codegen/generators/llvm.rs, src/codegen/tests/code_gen_tests.rs, src/index/visitor.rs, src/lexer.rs, src/lexer/tests/lexer_tests.rs, src/parser.rs, src/parser/expressions_parser.rs, src/parser/tests/expressions_parser_tests.rs, src/parser/tests/parser_tests.rs, src/typesystem.rs
WSTRINGs work like Strings, the data is stored in utf16-byte arrays
WSTRING literals are denoted using the double-ticks "
added mdbook entries for STRING and WSTRING
closes #171
=> WSTRING support

.github/workflows/rust.yml, src/codegen/generators/pou_generator.rs
Fixes #183 
Adds support to build on windows
Adds build artefacts for ubuntu and windows binaries.
=> Add Artifact support

.github/workflows/rust.yml, book/src/using_rusty.md, src/cli.rs, src/main.rs
This will resolve #172 
Changes:
* No output format choice will fallback to default, which is "--static"
* Default can easily be changed by modifying a single constant
* Output filenames are automatically given the correct extension based on the file format
* Additional tests that cover the new behaviour
=> Default CLI options

src/lib.rs, src/parser.rs, src/parser/tests/container_parser_tests.rs
Closes #206 
Uses a best-effort method to find the POU name (Last POU in the list)
If no POU is found, the name unknown is added as a container.
A diagnostic is produced if the name is missing.
=> Allow action container to inherit its name

tests/integration/external_files.rs
two integration tests cause cargo watch to build
in an endless loop.
=> ignore tests added in 55286718

.github/workflows/rust.yml, src/index/tests/index_tests.rs, src/parser.rs, src/parser/tests/parse_errors/parse_error_statements_tests.rs, src/parser/tests/variable_parser_tests.rs
Declare multiple variables with the same type in a single line. Closes #204.
=> Single line variable declarations

src/parser.rs, src/parser/tests/parse_errors/parse_error_literals_tests.rs
Allows string size expressions to be wrapped in round parentheses as well. Whenever this occurs, a diagnostic is going to be wrapped. Mismatched types of parentheses will also cause a diagnostic to be raised.
This will resolve #209.
=> Parentheses with string size arguments

src/main.rs
=> Fix invalid filenames not printing an error

src/ast.rs, src/codegen/generators/expression_generator.rs, src/codegen/generators/pou_generator.rs, src/codegen/generators/statement_generator.rs, src/codegen/llvm_typesystem.rs, src/index.rs, src/index/tests/index_tests.rs, src/index/visitor.rs, src/lexer.rs, src/lib.rs, src/parser.rs, src/parser/control_parser.rs, src/parser/expressions_parser.rs, src/parser/tests.rs, src/parser/tests/expressions_parser_tests.rs, src/parser/tests/misc_parser_tests.rs, src/parser/tests/parse_errors/parse_error_containers_tests.rs, src/parser/tests/parse_errors/parse_error_literals_tests.rs, src/parser/tests/parse_errors/parse_error_statements_tests.rs, src/parser/tests/statement_parser_tests.rs, src/parser/tests/type_parser_tests.rs, src/resolver.rs, src/resolver/tests.rs, src/resolver/tests/resolve_expressions_tests.rs, src/resolver/tests/resolve_literals_tests.rs, src/typesystem.rs
merged master and introduced the discussed issues:
- integer literals are now treated as DINT or LINT.
- negative integer-literals are no longer parsed as Unary-Statements but really parsed as negative numbers
will add issue for:
- currently we cannot derive a correct type name for array-literals and struct-literals
=> Literals type annotation

tests/integration/external_files.rs
Avoid infinite loop while compiling the integration tests
by using a temp folder.
=> Compile in temp for integration tests

codecov.yml
Don't fail on code coverage report.
Taken from https://docs.codecov.com/docs/common-recipe-list
We can also keep it required but make it more forgiving
=> Make codecov informational

src/codegen.rs, src/codegen/tests.rs, src/lib.rs, src/resolver.rs
we dropped the idea of importing everything into one big
compilation unit. instead we now do multiple calls to the
generator - one for every parsed compilation unit.
=> make annotations available in codegen

src/codegen/generators/data_type_generator.rs, src/codegen/llvm_index.rs, src/codegen/tests/code_gen_tests.rs, src/index.rs, src/index/tests/index_tests.rs, src/index/visitor.rs, src/lexer.rs, src/lexer/tests/lexer_tests.rs, src/lexer/tokens.rs
Add support for keywords and identifiers written using different cases
Closes #246 
TODO:
=> Support case insesitive keywords

book/src/build_and_install.md
Had some trouble getting rusty to build on ubuntu with a few conflicting LLVM installations, so I updated the docs with some tips for troubleshooting.
=> Docs: Add troubleshooting tips

.devcontainer/Dockerfile
added missing dependencies to Dockerfile
these dependencies are necessary since #243
=> add liblld-dev and llvm-dev to dockerfile apt's

src/lexer.rs, src/lib.rs
can generate unique Ids. Clones share a common
state to generate globally unique Ids (using Arc)
closes #281
=> introduce IdProvider using AtomicUsize

Cargo.lock, Cargo.toml, src/ast.rs, src/codegen/generators/data_type_generator.rs, src/codegen/generators/expression_generator.rs, src/codegen/generators/pou_generator.rs, src/codegen/generators/struct_generator.rs, src/codegen/generators/variable_generator.rs, src/codegen/llvm_typesystem.rs, src/index.rs, src/index/const_expressions.rs, src/index/tests/index_tests.rs, src/index/visitor.rs, src/parser.rs, src/typesystem.rs
const expressions are no longer stored directly in the index
but they are stored in an arena. This way it is easier to
replace them later when we want to resolve the expressions
into literals.
~~dedicated ConstExpressions-Tests still missing~~
=> arena implementation for const-expressions

tests/correctness/arrays.rs, tests/correctness/bitaccess.rs, tests/correctness/classes.rs, tests/correctness/control_flow.rs, tests/correctness/custom_datatypes.rs, tests/correctness/datatypes.rs, tests/correctness/external_functions.rs, tests/correctness/functions.rs, tests/correctness/global_variables.rs, tests/correctness/initial_values.rs, tests/correctness/pointers.rs, tests/correctness/sub_range_types.rs, tests/correctness/sums.rs, tests/tests.rs
To support tests where the main function returns values other than INT, we introduced an extra type parameter U to the compile and run
This has the side effect that the type of the result should now be specified and cannot always be inferred (in fact it can't be inferred in any of the tests)
=> Make compile and run return a generic type

src/ast/pre_processor.rs, src/index/tests/index_tests.rs, tests/correctness/pointers.rs
=> Preprocess arrays and pointers

src/lib.rs, src/validation.rs, src/validation/tests.rs, src/validation/tests/variable_validation_tests.rs, src/validation/variable_validator.rs
add validation rules that check:
- if all constants got initialized
- variable-initialization can be resolved
=> Validation constants need initializers issue294

src/codegen/generators/struct_generator.rs, src/index.rs, src/index/const_expressions.rs, src/index/tests/index_tests.rs, src/index/visitor.rs, src/lib.rs, src/resolver/const_evaluator.rs, src/resolver/tests/const_resolver_tests.rs, src/typesystem.rs, src/validation/tests/variable_validation_tests.rs, src/validation/variable_validator.rs
1. fb-instances and class-instances cannot be declared
as constants.
>    the implementation does not allow to declare a const
>    of type FB or Class, an array of FBs or Classes
>    or a struct that contains a field of type FB or
>    Class.
>    
>    Furthermore the DataTypeInformation::Struct now contains
>    a new field: 'source' that indicates where this struct
>    comes from. It is either an original Declaration
>    (TYPE x : STRUCT ... END_TYPE) or it was generated
>    from a POU(PouType). With this field it is now very
>    easy to see what a DataType offers (is it an FB or Class,
>    can I call it, etc.)
>    
>    closes #295
2. add scope to unresolved const expressions
>     the additional scope parameter in const_evaluator::evaluate(...)
>     helps the evaluator to …
=> Constants validation (fb instances not allowed #295, scoped const expressions #292)

src/codegen/generators/variable_generator.rs, src/codegen/tests/code_gen_tests.rs, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__arrays_are_generated.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__arrays_with_global_const_size_are_generated.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__structs_are_generated.snap, tests/correctness/global_variables.rs
especially complex global variables (arrays, struct) need
an initial value, or llvm will generate them as a external.
So when accessing that global variable it would result in an
ACCESS_VIOLATION
fixes #361
=> use default initializer for uninitialized globals

book/src/build_and_install.md
After some time I tried building the project again. Luckily, the build instructions still work like a charm (at least for me), except the LLVM version is now 12. Also it seems that the polly lib is required for most linux distros, and not just occasionally for troubleshooting. So I updated that in the description as well :)
=> Update LLVM version in build and install docs

src/codegen/generators/expression_generator.rs, src/codegen/generators/statement_generator.rs, src/codegen/llvm_typesystem.rs, src/codegen/tests/expression_tests.rs, src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__cast_lword_to_pointer.snap, src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__cast_pointer_to_lword.snap, src/resolver.rs, src/resolver/tests/const_resolver_tests.rs, src/resolver/tests/resolve_expressions_tests.rs, src/resolver/tests/resolve_generic_calls.rs, src/resolver/tests/resolve_literals_tests.rs, src/test_utils.rs
=> #353 assigning pointer-address to DWORD and vice versa

src/codegen.rs, src/codegen/generators/data_type_generator.rs, src/codegen/generators/expression_generator.rs, src/codegen/generators/pou_generator.rs, src/codegen/generators/statement_generator.rs, src/codegen/generators/variable_generator.rs, src/codegen/tests/code_gen_tests.rs, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__for_statement_continue.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__for_statement_int.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__for_statement_lint.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__for_statement_sint.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__for_statement_with_exit.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__for_statement_with_references_steps_test.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__for_statement_with_steps_test.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__for_statement_without_steps_test.snap, src/lib.rs, src/resolver.rs, src/resolver/tests/const_resolver_tests.rs, src/resolver/tests/resolve_control_statments.rs, src/resolver/tests/resolve_expressions_tests.rs, src/resolver/tests/resolve_generic_calls.rs, src/resolver/tests/resolve_literals_tests.rs, src/test_utils.rs, src/validation.rs, src/validation/stmt_validator.rs, tests/correctness/control_flow.rs
For loops counter variables were overflowing into other variables if the size was less than 32bit
Also decrement was not working correctly
We now correctly annotated the type for the for loop variables and we check if the counter is between the specified values.
=> Fix for loop behaviour

src/codegen/generators/statement_generator.rs, src/codegen/llvm_typesystem.rs, src/codegen/tests/snapshots/rusty__codegen__tests__statement_codegen_test__function_result_assignment_on_aliased_string.snap, src/codegen/tests/snapshots/rusty__codegen__tests__statement_codegen_test__function_result_assignment_on_string.snap, src/codegen/tests/snapshots/rusty__codegen__tests__string_tests__function_parameters_string.snap, src/codegen/tests/snapshots/rusty__codegen__tests__string_tests__variable_string_assignment_test.snap, src/codegen/tests/statement_codegen_test.rs, tests/correctness/strings.rs, tests/tests.rs
Fixes #389 
Call statements now use an intermediate allocated variable to store the result of a string.
This variable is then written to the assignment using memcpy.
The size of the mem copy no longer uses the hint, but the actual string size.
=> Issue 389 strings assignments don't work on function calls

src/resolver.rs, src/resolver/tests/resolve_expressions_tests.rs, src/resolver/tests/resolve_literals_tests.rs, src/typesystem.rs
now that the annotator is able to create new types on the fly, we
can create correct string-types when visiting literals and annotate
the literal with the newly created type.
=> annotate string literals with correct length

src/lib.rs, src/runner.rs, tests/tests.rs
This allows reuse of the compile/run methods we use in the correctness tests by other crates such as the Standard Functions
=> Extract the test run code from  into a runner module

src/index.rs, src/index/tests/index_tests.rs, src/index/visitor.rs
var_in_out pointers and normal pointers need different names
so they dont overwrite each other since they have a different
auto_deref seeting.
fixes #461
=> auto-deref pointer need unique type name

src/parser.rs, src/tests/external_files.rs, src/tests/snapshots/rusty__tests__external_files__external_file_global_var.snap
Fixes #454 
Made sure the parser does not loose its linkage parameter.
=> Issue 454 global variables in external files are not working

scripts/build.sh
Add support to generate a junit report in the build scripts.
The workflows on github remain unchainged
=> Add an option to generate test reports for junit

scripts/build.sh
The junit report generated by cargo is not formatted correctly
This is because the underlying library (libtest) will generate a report per test class (unit/integration)
libtest expects the tests to be run individually
The script will now run unit tests and the integration tests
It also removes the leading empty line from the result
=> Split the junit report into multiple files, and move it to test results

src/ast.rs, src/parser.rs, src/parser/tests/expressions_parser_tests.rs, src/parser/tests/function_parser_tests.rs, src/parser/tests/misc_parser_tests.rs, src/validation/pou_validator.rs, src/validation/tests.rs, src/validation/tests/pou_validation_tests.rs
Functions with missing return types used to report a problem on the
whole POU (declaration and body). I added an additional location field
to the POU (AST) that stores the location of the POU's name so we can
report the error more nicely where it actually happened.
also activated dead test (pou_validation_tests)
resolves #491
=> improved validation of FUNCs without return types

src/codegen/tests/generics_test.rs, src/codegen/tests/snapshots/rusty__codegen__tests__generics_test__generic_output_parameter.snap, src/index.rs, src/resolver.rs, src/resolver/tests/resolve_generic_calls.rs
VAR_OUTs used to confuse the resolver to find out what
real type T is, if T is defined by a VAR_OUT or VAR_INOUT
since its real type was no longer 'T' but rather 'POINTER TO
T'.
fixes #499
=> generic function types can be determined by VAR_OUT

.github/workflows/rust.yml, .gitpod.yml, src/codegen/generators/expression_generator.rs, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__program_with_special_chars_in_string.snap, src/codegen/tests/snapshots/rusty__codegen__tests__code_gen_tests__program_with_string_assignment.snap, src/codegen/tests/snapshots/rusty__codegen__tests__string_tests__program_with_casted_string_assignment.snap, src/codegen/tests/snapshots/rusty__codegen__tests__string_tests__program_with_string_type_assignment.snap, src/codegen/tests/snapshots/rusty__codegen__tests__string_tests__variable_length_strings_can_be_created.snap, src/codegen/tests/snapshots/rusty__codegen__tests__string_tests__variable_length_strings_using_constants_can_be_created.snap, src/typesystem.rs, tests/correctness/strings.rs
When `memcpy`ing WSTINGS the size is now doubled as the memcpy is always resulting in an i8 copy
I added correctness tests to make sure WSTRINGS are assigned correctly.
I also fixed the windows build
Fixes #502
=> WSTRINGs assignment now use the full WSRTING size

.gitpod.yml
The prebuild should now also have a compiled version of rusty
Meaning subsequent builds should be faster.
<a href="https://gitpod.io/#https://github.com/PLC-lang/rusty/pull/503"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add init tasks for gitpod to run a cargo build

src/cli.rs, src/lib.rs, tests/integration/external_files.rs, tests/integration/linking.rs
Hi guys, hope you're doing well! I had some spare time, so I thought I'd catch up with the project and drop you a PR. Things are moving quickly...!
This should fix #482.
I split up `compile_module()` into `index_module()` and `compile_module()` so that the two can be called independently (the check option then only calls index_module and doesn't generate code).
Hope it helps!
=> Add validation-only flag (--check)

src/diagnostics.rs, src/index.rs, src/index/tests/snapshots/rusty__index__tests__instance_resolver_tests__global_struct_variables_are_retrieved.snap, src/index/tests/snapshots/rusty__index__tests__instance_resolver_tests__nested_global_struct_variables_are_retrieved.snap, src/index/visitor.rs, src/resolver.rs, src/resolver/tests/resolve_expressions_tests.rs, src/validation/stmt_validator.rs, src/validation/tests/reference_resolve_tests.rs
an illegal access diagnostic is added when accessing a private field
from outside the declaring pou. private fields are VAR & VAR_TEMP
declarations.
the compiler will successfully resolve the reference (and following
ones) to avoid follow-up errors.
fixes #55
<a href="https://gitpod.io/#https://github.com/PLC-lang/rusty/pull/513"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> access to VAR/VAR_TEMP from outside the declaring pou is illegal

.github/workflows/rust.yml
The original toolchain is unmaintained, see https://github.com/actions-rs/toolchain/issues/216
<a href="https://gitpod.io/#https://github.com/PLC-lang/rusty/pull/521"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Use dtolnay/rust-toolchain

src/validation/stmt_validator.rs, src/validation/tests/reference_resolve_tests.rs
The validator now looks at container names when validating
<a href="https://gitpod.io/#https://github.com/PLC-lang/rusty/pull/526"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Make sure the private variable validator allows actions

src/cli.rs, src/resolver.rs, src/resolver/generics.rs, src/resolver/tests/resolve_expressions_tests.rs, src/resolver/tests/resolve_generic_calls.rs, tests/correctness/generic_functions.rs
Generic functions with by ref variables like VAR_IN_OUT or VAR_INPUT {ref} were failing to generate.
This was due to pointers not being recreated in the new types
This change fixes that behaviour and adds tests for different by ref cases.
<a href="https://gitpod.io/#https://github.com/PLC-lang/rusty/pull/543"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Generics passed by referenced can be resolved

book/src/build_and_install.md, book/src/using_rusty.md, book/src/using_rusty/build_description_file.md, examples/hello_world.st, src/cli.rs, src/lib.rs, src/linker.rs, tests/integration/data/linking/relative.st, tests/integration/linking.rs
Fixes #548  and #551 
The linker will no longer try to add an empty parent directory to the
linked directory (`-L`)
The cc linker will now output its results to stdio/stderr and return an
error if the compilation fails
Updated the hello_world documentation
Update the documentation to mention llvm13 instead of 12 for
installation
Add information about target and sysroots in the build
<a href="https://gitpod.io/#https://github.com/PLC-lang/rusty/pull/552"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix the linking issues when the path is relative

src/parser/expressions_parser.rs, src/parser/tests/control_parser_tests.rs, src/parser/tests/expressions_parser_tests.rs
call parameters and case-statements may have trailing commas that made the parser stumble.
example: `foo(1,2,3,);` or
```
CASE x OF
1,2,3,: ...
```
fixes #579
<a href="https://gitpod.io/#https://github.com/PLC-lang/rusty/pull/583"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> allow trailing comma in expression lists

tests/correctness/expressions.rs
Issue seems to be fixed already. Are there any other tests we should do? 
<a href="https://gitpod.io/#https://github.com/PLC-lang/rusty/pull/596"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adds correctness test for aliased ranged number comparison

src/validation/stmt_validator.rs, src/validation/tests/statement_validation_tests.rs, tests/correctness/expressions.rs
Trying to compare subranges still caused a SyntaxError (for aliased and non-aliased types):
```
PROGRAM main
VAR 
a : BOOL;
END_VAR      
VAR_TEMP
x,y : INT(0..500);
END_VAR
a := x < y;
END_PROGRAM
```
```
` message: "Missing compare function 'FUNCTION __main_x_LESS : BOOL VAR_INPUT a,b : __main_x; END_VAR ...'.",`
```
This happened during statement validation because the validator was looking for a function matching the SubRange name, not its referenced type.
This pull request resolves that issue.
<a href="https://gitpod.io/#https://github.com/PLC-lang/rusty/pull/598"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> 586 custom aliased int types cannot be compared

src/lexer/tests/lexer_tests.rs, src/parser/expressions_parser.rs
changes the expression parser to also accept uppercase time literals.
=> 660 time literals are case sensitive

src/codegen/generators/pou_generator.rs, src/codegen/tests/initialization_test/global_initializers.rs, src/codegen/tests/initialization_test/snapshots/rusty__codegen__tests__initialization_test__global_initializers__global_constant_without_initializer_gets_declared_initializer.snap, src/codegen/tests/initialization_test/snapshots/rusty__codegen__tests__initialization_test__global_initializers__global_constant_without_initializer_gets_default_initializer.snap
aggregate local constant variables (in functions) used to have problems if they were not properly initialized. Instead of forcing an initializer, we fallback to the type's default value or zeroinitializer.
added regression test for a previously failing situation
fixes #634
=> initialize local VAR CONSTANT function vars

src/builtins.rs, src/codegen/tests/expression_tests.rs, src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__builtin_function_call_sizeof.snap, src/resolver/tests/resolve_expressions_tests.rs, src/validation/tests/duplicates_validation_test.rs, tests/correctness/functions.rs, tests/correctness/math_operators/addition.rs, tests/correctness/math_operators/division.rs, tests/correctness/math_operators/mixed.rs, tests/correctness/math_operators/multiplication.rs, tests/correctness/math_operators/substraction.rs
Adds builtin sizeof function and fixes various clippy lints (chrono deprecated function calls, ...) and some typos
=> 642 add sizeof builtin function

.cargo/config.toml, .devcontainer/Dockerfile, .gitignore, book/src/build_and_install.md, scripts/lld.sh
@ghaith and I conducted some tests regarding performance differences between `lld` and `mold` on our workstations and came to the conclusion that there's (almost) hardly a difference. For reference those were my recorded times on my local VM
```bash
default: 9.16s, 8.47s, 8.23s
lld:     4.78s, 4.80s, 4.86s
mold:    4.28s, 3.76s, 3.90s
```
Because of that we decided to stick with `lld` since the installation of it is much simpler, i.e. `lld` is present on most Linux distributions whereas `mold` has to be compiled manually and may need additional dependencies. Furthermore we decided to give control over to the developer by not forcing anyone to use `lld` by default. The motivation behind this was because builiding the project may result in linker errors otherwise since we do not know if …
=> Improve compile times (#679)

book/src/build_and_install.md, book/src/pous.md
- Replace `.bashrc` with `.zshrc` in MacOS build instructions because zsh is the default shell
- Fix markdown link in POUs section
=> Minor documentation changes

src/diagnostics.rs, src/validation.rs, src/validation/tests/statement_validation_tests.rs
Kind of fixes #698 where previously something like
```ST
FUNCTION func : DINT 
VAR_INPUT {ref}
byRefInput : INT;
END_VAR 
VAR_INPUT
byValInput : INT;
END_INPUT
END_FUNCTION
PROGRAM main
func(1, 2); // This should be invalid because the first argument is expected
// to be a reference  but we pass a integer literal here
func(x, 2); // This is what a valid function call should look like
END_PROGRAM
```
was accepted. When running with the `verify` feature enabled this would result in errors however, because the LLVM IR is not what one would expect it to be. Instead of fixing the LLVM IR generated code, we settled with a validation solution since this code should in general be invalid.
=> Disallow passing literals as function arguments where references are expected (#698)

.github/workflows/doc.yml, .github/workflows/rust.yml
While we update the rust llvm repo to version 1.67/LLVM 14 we force the current builds to stay on 13 until the move is done
=> Force the docker version to remain on 13

book/src/build_and_install.md
Fixes https://github.com/PLC-lang/rusty/issues/757
Edit: Tested on my machine and it seems to be working with binaries downloaded from our build servers which previously failed.
=> Add libffi7 to 'Build & Install' book chapter

book/src/SUMMARY.md, book/src/build_and_install.md, book/src/development_tips.md
- Added a `Development Tips` chapter, transfering the `Improving Compile Times` section to it
- Merged the `Building` section with the introduction section of `Build & Install`
=> Clean-up `Build & Install` section

Cargo.toml, book/src/build_and_install.md, src/typesystem.rs, src/validation/tests/statement_validation_tests.rs
Fixes https://github.com/PLC-lang/rusty/issues/759
Trying to pass an array as a function argument triggered a validation error
because we we're checking if the passed argument is of the same type as the declared
parameter. The detection of such code in the `is_same_type_class` function was non-existing however.
This commit adds such a check such that passing array arguments is allowed.
=> Allow arrays to be passed as function arguments

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This will currently not work on AARCH64 hosts like the M1/M2 because the base image is not (yet) available.
The docker file is currently only needed because of the chmod and the insta installation commands, i think we could move both to a devcontainer build on the rust-llvm-images side
=> Update the dev container to the latest build script

book/src/arch/codegen.md, book/src/arch/linker.md, book/src/arch/parser.md, book/src/arch/validation.md, book/src/build_and_install.md, book/src/datatypes.md, book/src/direct_variables.md, book/src/libraries.md, book/src/libraries/external_functions.md, book/src/pous.md, book/src/using_rusty.md, book/src/using_rusty/build_configuration.md
This PR contains the following changes:
1. Correctly display tables in the book, which are currently broken due to missing newlines; see https://plc-lang.github.io/rusty/arch/validation.html
2. Remove whitespace between words and colons, e.g. `Example :` becomes `Example:`
3. Add the recursive and global validators to the Validation table
=> Book fixes

examples/lt.st, src/ast.rs, src/codegen/generators/statement_generator.rs, src/codegen/tests/expression_tests.rs, src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__allowed_assignable_types.snap, src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__assigning_of_arrays_and_pointers_allowed.snap, src/codegen/tests/snapshots/rusty__codegen__tests__expression_tests__hardware_access_assign_codegen.snap, src/validation/stmt_validator.rs, src/validation/tests/statement_validation_tests.rs
The validator for invalid assignment will now no longer trigger on Arrays/Pointers and Bitaccess
This is ideally just a temporary solution.
A better solution would include refactoring the Resolver/Annotations to separate between LValues and RValues on that level.
=> Allow assigniment of Array/Pointer/Direct Access

src/tests/adr.rs, src/tests/adr/arrays_adr.rs, src/tests/adr/strings_adr.rs, src/tests/adr/structs_adr.rs
introduce the architecture design records for aggreate datatypes
=> ADR documentation (arrays, strings, structs)

.gitignore
JetBrains related IDEs such as CLion create a `.idea/` folder which can be ignored
=> Ignore `.idea/` folder

src/validation/tests.rs, src/validation/tests/array_validation_test.rs, src/validation/tests/assignment_validation_tests.rs, src/validation/tests/bitaccess_validation_test.rs, src/validation/tests/duplicates_validation_test.rs, src/validation/tests/generic_validation_tests.rs, src/validation/tests/literals_validation_tests.rs, src/validation/tests/pou_validation_tests.rs, src/validation/tests/recursive_validation_tests.rs, src/validation/tests/reference_resolve_tests.rs, src/validation/tests/statement_validation_tests.rs, src/validation/tests/variable_validation_tests.rs
Refactored `assert_snapshot!(make_readable(&diagnostics))` to `assert_validation_snapshot!(&diagnostics)`
=> Simplify snapshot assertion

.vscode/launch.json
(Nit of mine) Adds entries to the `launch.json` file allowing us to debug a unit test and/or a ST file called `demo` and `demo.st` respectively with a simple button click.
=> Add `launch.json` debug entries

.cargo/config.toml
MacOS still has some issues when specifiying lld as the default linker. Might create another PR for that specifically if I find a fix, but compiling under M1 is currently fast enough.
=> Make LLD the default linker for Linux x86_64

.cargo/config.toml, .github/workflows/metrics.yml, Cargo.toml, xtask/src/metrics/oscat.rs
This commit does two things:
1) No longer clone https://github.com/PLC-lang/StandardFunctions for the metrics workflow, because of https://github.com/PLC-lang/rusty/pull/836
2) Add `rustyc` and remove `xtask` from the `default-members` entry
=> Update metrics workflow

Cargo.lock, Cargo.toml, libs/stdlib/Cargo.toml, rusty-derive/Cargo.toml, rusty-derive/src/lib.rs, rusty-derive/tests/rusty_derive_tests.rs, src/validation.rs, src/validation/global.rs, src/validation/recursive.rs
While working on adding a Validator to the builtins, I have noticed that all the implementations for the Validators trait are exactly the same, so I've looked into proc-macro-derives. It might not be a huge improvement for this particular use-case, but considering we are planning on refactoring the visitor, AST and utilize more traits in general, I think this language feature might come in handy in future.
Feel free to leave your thoughts about this/discuss, I won't be upset if it doesn't end up being merged :)
=> Add proc-macro support for custom derives

libs/stdlib/iec61131-st/extra_functions.st, libs/stdlib/tests/extra_function_tests.rs
This PR introduces the following stdlib functions 
- `USINT_TO_STRING`
- `UINT_TO_STRING`
- `UDINT_TO_STRING`
- `ULINT_TO_STRING`
=> Add unsigned integers to string conversion

src/codegen/generators/expression_generator.rs, src/codegen/generators/statement_generator.rs, src/codegen/generators/variable_generator.rs, src/codegen/llvm_typesystem.rs
Adds a convenience macro for the cast_if_needed function which allows calling it with fewer parameters.
=> cast-if-needed convenience macro

libs/stdlib/scripts/build.sh, scripts/build.sh, tests/correctness/pointers.rs
Rust nightly is required for the junit test format option, this was not failing previously for some reason
I also fixed a test that fails with nightly.
=> Make sure cargo works on nightly with junit

libs/stdlib/build.rs
This should fix the issue where cargo is rebuilding the standard library even without any changes. Found the issue via https://doc.rust-lang.org/cargo/faq.html#why-is-cargo-rebuilding-my-code. Specifically when running `cargo build` with `CARGO_LOG=cargo::core::compiler::fingerprint=info cargo build` we previously got the following log message
```
[2023-06-20T11:51:52Z INFO  cargo::core::compiler::fingerprint]     dirty: FsStatusOutdated(StaleItem(MissingFile("/home/volkan/Desktop/rusty/libs/stdlib/iec61131-st/*")))
```
Removing the `*` from the path seems to fix it on my machine(TM)
=> Fix cargo rebuilding issue

.vscode/launch.json, src/linker.rs
Fixes issues where running a VS Code debug configuration failed due to naming issues. 
Off-topic but does anyone actually use all these configurations defined in `launch.json`? I see myself only using the `Debug source 'demo.st'` and `Debug unit test 'demo'` configuration, maybe we can remove some configuration if they're unused?
=> Update `launch.json` to reflect workspace introduction

src/linker.rs
Running `cargo b -p iec61131std` previously returned linking errors on macOS which this PR fixes by using clang as well as the `-r` flag instead of `--relocatable`. Both these flags should be equivalent although the latter isn't recognized on clang.
EDIT: Unrelated to the linking issue, I've also deduplicated some linker code by using a trait default implementation
=> Fix linking issue on macOS

src/codegen/tests/initialization_test/snapshots/rusty__codegen__tests__initialization_test__type_initializers__array_of_struct_initialization_with_brackets.snap, src/codegen/tests/initialization_test/type_initializers.rs, src/resolver.rs, tests/correctness/arrays.rs
Resolves https://github.com/PLC-lang/rusty/issues/895
=> Allow initialization of array with struct elements using bracket symbol

src/validation/statement.rs, src/validation/tests/snapshots/rusty__validation__tests__reference_resolve_tests__resole_struct_member_access.snap, src/validation/tests/snapshots/rusty__validation__tests__reference_resolve_tests__resolve_function_block_calls_in_structs_and_field_access.snap, src/validation/tests/snapshots/rusty__validation__tests__reference_resolve_tests__resolve_function_members_via_qualifier.snap, src/validation/tests/snapshots/rusty__validation__tests__statement_validation_tests__bit_access_with_incorrect_operator_causes_warning.snap, src/validation/tests/statement_validation_tests.rs
This PR introduces a warning when a bit-access is attempted with the `.`-operator. If the type that is bit-accessed does not have a type annotation (i.e. POUs, unresolved refs), no warning will be given.
This will not hint at attempts to use bit-access with qualified variables as indices.
E.g. `prog.baz.var1.prog.baz.var2`, will just result in unresolved reference warnings. Here a hint to the user allowed would be helpful, but it is not trivial to know what the user attempts here - everything after `.var1` will be unresolved.
=> Give a warning when trying to access bits without using the %X operator

src/diagnostics.rs, src/validation/snapshots/rusty__validation__variable__variable_validator_tests__validate_enum_variant_initializer.snap, src/validation/statement.rs, src/validation/tests/snapshots/rusty__validation__tests__assignment_validation_tests__enum_variants_mismatch.snap, src/validation/variable.rs
Fixes invalid enum initializers not being validated. I've also reclassified the severity from `ImprovementSuggestion` to `SemanticError`. Consider the following example:
```
PROGRAM prog
VAR
x : DINT := 12345;
var3 : (a, b, c) := 7; // this should not just be a warning
END_VAR
var3 := x; // and neither should this
END_PROGRAM
```
While we could validate against a literal initializer out of range, doing so for a reference is a different story.
=> enum initialization in var-blocks

libs/stdlib/iec61131-st/string_functions.st, libs/stdlib/src/string_functions.rs, tests/integration/command_line_compile.rs
fixes #920
String equality comparison functions were missing resolved-type header implementations (e.g. GT__STRING) with the proper variadic signature.
=> fix `string_functions.st` error when compiled to IR

compiler/plc_driver/src/cli.rs, compiler/plc_driver/src/pipelines.rs, compiler/plc_project/src/project.rs, src/codegen.rs, src/output.rs
Also fixed an issue with the default name overwriting the input, the output name is now <input>.out if not specified
Fixes #792 and #936
=> Make shared and PIC the same, add no-pic option

Cargo.lock, compiler/plc_diagnostics/src/diagnostician.rs, compiler/plc_diagnostics/src/diagnostics.rs, compiler/plc_diagnostics/src/errno.rs, compiler/plc_diagnostics/src/reporter/codespan.rs, compiler/plc_driver/src/lib.rs, compiler/plc_driver/src/pipelines.rs, compiler/plc_source/src/source_location.rs, compiler/plc_xml/src/xml_parser.rs, src/parser.rs, src/test_utils.rs, tests/integration/linking.rs
When outputing errors from codegen, we now report them the same way as normal errors.
We also can now abort on critical errors.
=> Better diagnotics in codegen

Cargo.lock, Cargo.toml, compiler/plc_driver/Cargo.toml, compiler/plc_xml/Cargo.toml, xtask/Cargo.toml
This PR bumps the following dependencies 
- quick-xml, 0.28 -> 0.30
- itertools, 0.10.5 -> 0.11
- sysinfo, 0.28 -> 0.29
- indexmap, 1.* -> 2.0
Dependencies such as logos, clap and toml are still outdated, but given they'll need bigger changes I've left them out for now.
=> chore: Bump `indexmap`, `sysinfo`, `itertools` and `quick-xml`

Cargo.lock, Cargo.toml
Since inkwell recently pushed  [breaking API-changes](https://github.com/TheDan64/inkwell/commit/d39987b58a63913612fc80b093d2b805fae805ff) to their master branch, which we currently have as a dependency, we are unable to build ruSTy on new cargo installs or after running cargo-update.
This PR changes our inkwell-dependency to their latest release version [0.2](https://github.com/TheDan64/inkwell/releases/tag/0.2.0), which already includes the contribution by @ghaith we depend on/which was the reason for our dependency on their master branch.
=> chore(inkwell-dependency): change inkwell dependency from master to release 0.2

.cargo/config.toml
Compiling on Windows with 
```
[target.x86_64-pc-windows-msvc]
linker = "lld-link"
```
results in the following error `note: lld-link: error: could not open 'link': no such file or directory`. Works fine without it however.
=> fix: Windows compilation

compiler/plc_xml/src/xml_parser/block.rs, src/resolver.rs, tests/integration/cfc.rs, tests/integration/cfc/resolver_tests.rs, tests/integration/data/cfc/function_block_call_fb.cfc, tests/integration/data/cfc/function_block_call_main.cfc
Whenever we encountered a CFC block element, we previously created call statements based on it's `typeName`. While this is correct for function calls, it is incorrect for function block calls where it should have been the `instanceName`. To better illustrate the issue, here's the culprit `<block localId="4" width="137" height="80" typeName="myFb" instanceName="fb0" executionOrderId="0">`.
This issue has been fixed by using the `instanceName` before falling back to the `typeName`.
=> fix(cfc): Call statements for function blocks

.github/workflows/rust.yml, Cargo.toml, book/src/using_rusty/build_configuration.md, compiler/plc_project/Cargo.toml, compiler/plc_project/src/build_config.rs, src/parser/tests/expressions_parser_tests.rs, src/resolver/tests/resolve_expressions_tests.rs
Schema validation now happens from the current binary location. In tests, it still uses the source location.
If no schema is found, validation is skipped.
=> fix:  validations when out of source now use bin location

src/validation/array.rs, src/validation/tests/array_validation_test.rs, src/validation/tests/snapshots/rusty__validation__tests__array_validation_test__parenthesized_struct_initializers.snap
Add a validation for single assignment statements in array of struct initializer, e.g. `foo : ARRAY[...] OF MyStruct := [myField := 0]` returns a codegen error (Some initial values were not generated) with no validation error. This PR introduces a validation for that edge-case.
=> fix(validation): Single assignment statements in array of struct initializer

libs/stdlib/iec61131-st/endianness_conversion_functions.st, libs/stdlib/src/endianness_conversion_functions.rs, libs/stdlib/tests/endianness_conversion_functions_tests.rs
Currently endian conversion functions work mostly very wrong. Also most of the test would also break in BE system.
Only TO_*_ENDIAN() for other than float types does what they should. FROM_*_ENDIAN() for other than float types does conversion totally wrong. Normally we would do in IEC something like this (PSEUDO):
address := FROM_LITTLE_ENDIAN(READ_MODBUS_ADDRESS_DWORD());
Now we would get big endian address even if we just wanted to document that we have checked that address should be little endian. In companies it is happit that every time they read/write to/from fieldbus they use FROM_*_ENDIAN/TO_*_ENDIAN conversion functions so it is obvious that it has been taken to account.
Also floating points did not do any conversions as they first convert to x endian and then convert back to …
=> fix(stdlib): Endian conversion functions

libs/stdlib/iec61131-st/timers.st, libs/stdlib/src/timers.rs, libs/stdlib/tests/timer_tests.rs
In our timer implementation we tracked the on/off state by checking whether or not the `start_time: Option<Instant>` field was a `Some`-Value. This led to a bug where the timer was always on, due to the `Option` value in a `Repr(C)` struct always being zero-initialized, and therefore always being a `Some` value.
I've added an internal boolean field to the timer-struct to track timer state and it seems to have fixed the issue.
Resolves #1047
=> fix(timers): add internal flag to track state

src/validation/statement.rs, src/validation/tests/snapshots/rusty__validation__tests__enum_validation_test__enum_variants_mismatch.snap
Resolves https://github.com/PLC-lang/rusty/issues/1119
=> feat(validation): Convert enum error to warning

compiler/plc_driver/src/runner.rs
No idea why we had this in the first place, but it just clutters the whole terminal with LLVM IR we (probably) are uninterested in.
=> refactor: Suppress printing of LLVM IR in test runs

tests/integration/build_description_tests.rs
`build_with_cc_linker` would previously always fail when running under macOS, which this PR fixes by adding a macOS triplet to the `--target` flag.
=> fix: Add macOS triplet to linking test

compiler/plc_driver/src/pipelines.rs
Fixes a bug for Windows where compilation would panic if the compiler was executed in another drive than where a project was located in. For example if `plc build D:/project/conf/plc.json [...]` was executed from the `C:/` drive, the pipeline would try to strip the root `C:/` from the path `D:/project/...` which panics because of the method [`strip_prefix`](https://doc.rust-lang.org/std/path/struct.Path.html#method.strip_prefix). For linux and macOS this was no problem because the root is always `/`.
=> fix: Derive root directory from unit

src/lexer.rs, src/parser.rs, src/parser/expressions_parser.rs
use `expect_token!()` instead of `lexer.expect()`. this deprecation is planned early in #196, but
didn't really be applied.
=> refactor: deprecate expect() in mod lexer(#196)

compiler/plc_driver/src/main.rs
When the compilation ends with a diagnostic with severity `Error`, we now no longer exit with `0` (Success) but rather `1` (Catchall for general errors, as defined in the [Linux Documentation Project](https://tldp.org/LDP/abs/html/exitcodes.html)). I've also looked at the [BSD standards](https://man.freebsd.org/cgi/man.cgi?query=sysexits&manpath=FreeBSD+4.3-RELEASE) (mirrored in the [exitcode crate](https://crates.io/crates/exitcode)) and, if we want to follow these guidelines, we could opt to change it to `65 - Data Error`, but I would suggest to stick with `1` for now until we decide on a more fine-grained exit approach for different error scenarios.
Refs: #817
=> feat: exit with error status on compilation failure

.github/workflows/rust.yml, compiler/plc_xml/src/xml_parser.rs, src/index/visitor.rs, src/parser.rs, src/validation/statement.rs
- Bumps the Windows Rust Version to 1.77 for test runs
- Applies 1.77 clippy and rustfmt suggestions
=> ci: Prepare for Rust 1.77 version bump

compiler/plc_driver/src/runner.rs
Should a integration/correctness-test result in a diagnostic, we now panic with the diagnostic as message instead of calling `unwrap` on the result in `runner::compile`.
This makes it easier to see the reason for why tests might have failed at a glance.
=> feat: show diagnostics in `panic` in `runner::compile`

.config/nextest.toml, scripts/build.sh
Updates the build-script to run junit tests with cargo-nextest instead of depending on the nightly rust toolchain.
=> ci: update build-script for nextest

src/codegen/generators/expression_generator.rs, src/codegen/tests/parameters_tests.rs, tests/correctness/functions.rs
Renames `generate_string_store` to `build_memcpy` and adapts the logic to work for all aggregate types, not just strings.
Resolves #1164
=> fix: aggregate output assignments

.cargo/config.toml, .github/workflows/rust.yml, .github/workflows/windows.yml
The windows and linux workflows are now split into 2 files
Each workflow can be enabled/disabled manually and reported manually.
=> ci: Split the windows and linux workflows

compiler/plc_ast/src/ast.rs, compiler/plc_ast/src/lib.rs, compiler/plc_ast/src/visitor.rs, src/builtins.rs, src/codegen/generators/expression_generator.rs, src/parser/tests.rs, src/parser/tests/ast_visitor_tests.rs, src/resolver.rs, src/validation/statement.rs
The AST-Visitor trait allows generic visiting of AST-nodes. A default Walking behavior is implemented for each AstStatement but it can be altered by any implementor. When overriding a visit_XXX method, the implementation can decide to continue with the default walking behavior (by calling the walk function on the passed AstStatement-Struct, to skip it, or to continue with an alternative walking bahavior.
The code could be improved with a derive-macro for the walker trait
=> refactor(AST): introduce AstVisitor trait

compiler/plc_driver/src/cli.rs, compiler/plc_driver/src/lib.rs, src/resolver.rs
Implements #1003
If the `--ast` is found, then after `Resolve / Annotate`, it prints the AST to stdout and then terminates.
Ideally this would be another output format that gets written to disk as JSON or something instead of emitted over stdout, but this is a start.
This just uses the default Rust Debug formatting.
For example:
```
target\debug\plc.exe examples/hello_world.st --ast
```
produced
```
[
(
CompilationUnit {
global_vars: [],
units: [
POU {
name: "puts",
variable_blocks: [
VariableBlock {
variables: [
Variable {
name: "text",
data_type: DataTypeReference {
referenced_type: "STRING",
},
},
],
variable_block_type: Input(
ByRef,
),
},
],
pou_type: Function,
return_type: Some(
DataTypeReference {
referenced_type: "DINT",
},
),
},
POU {
name: "main",
variable_blocks: [],
pou_type: …
```
=> feat: add --ast CLI argument to emit the AST to stdout

src/parser.rs
Fixes an issue where omitting a data-type in an alias variable would cause a panic in the parser. For example
```
FUNCTION main
VAR
s AT str; // omitted data-type
END_VAR
END_FUNCTION
```
=> fix: Pattern match Option value in alias variable

src/parser.rs, src/parser/tests/statement_parser_tests.rs
Previously a string REFERENCE TO pointer variable would fail to parse when a REF= operator was present. This commit fixes this by checking if a REF= operator can be consumed when parsing a STRING variable (line). Specifically the parser should now be able to parse the following without any issues
```
FUNCTION main
VAR
foo : REFERENCE TO STRING REF= bar;
bar : STRING;
END_VAR
END_FUNCTION
```
=> fix: Parse REFERENCE TO STRING initializer

src/index.rs
The `find_elementary_pointer_type` may cause a stackoverflow by recursively calling itself if an inner type of a pointer can not be found. Mainly because of the line `unwrap_or_else(|| initial_type)`.
=> fix: Potential stack-overflow in index look-up

scripts/build.sh
The container engine is currently selected automagically selected when building with the `--container` flag. This PR adds the functionality to specify the container engine used for building.
If `--container-engine <ENGINE>` is provided the script will try to build using the specified engine:
`build.sh --build --container --container-engine "podman"`
If `container-engine` flag is not provided the script will behave as before and try to auto-detect the engine and choose the first it finds.
=> build: add option to specify container engine

Cargo.lock, compiler/plc_ast/src/visitor.rs, src/codegen/generators/expression_generator.rs, src/index.rs, src/tests/adr/reference_expressions_adr.rs, src/validation/recursive.rs, tests/correctness/strings.rs, xtask/src/reporter.rs
This PR applies suggestions from `cargo {update,clippy,fmt}` for the Rust version bump from 1.77 to 1.80.1
=> chore: Prepare Rust version bump from 1.77 to 1.80.1

compiler/plc_ast/src/ast.rs, compiler/plc_ast/src/pre_processor.rs, src/index/tests/index_tests.rs, tests/lit/single/address/hardware_reference_used.st
Global addresses are now added to their own section
If a global has already been added, it will not be added again
=> fix: generated globals are not duplicates

src/index/tests/index_tests.rs, src/parser.rs, src/parser/tests/variable_parser_tests.rs
Previously the location of a variable name declared in a `VAR_CONFIG` block would include the `AT` keyword in it. With this commit the `AT` keyword is omitted such that a slice of the variable name is e.g. `main.instance.foo` instead of `main.instance.foo AT`.
=> fix: Location of variables declared in VAR_CONFIG

.github/workflows/linux.yml
Fixes an issue in the CI where the coverage action would not run because v1 and v2 of `upload-artifact` have been deprecated. 
See also https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
=> ci: Bump `upload-artifact` action from v1 to v4

compiler/plc_driver/Cargo.toml, compiler/plc_driver/build.rs, compiler/plc_driver/src/cli.rs, compiler/plc_driver/src/lib.rs
The `--version` flag now emits the date and hash of the latest commit in addition to the package version as specified in the `Cargo.toml` file.
=> refactor: Date and commit hash in --version flag

libs/stdlib/iec61131-st/arithmetic_functions.st, libs/stdlib/iec61131-st/date_time_numeric_functions.st, libs/stdlib/tests/date_time_numeric_functions_tests.rs
This commit changes the function signature of the ADD and MUL functions, i.e.
```diff
FUNCTION ADD < T1: ANY, T2: ANY >: T1
VAR_INPUT
IN1: T1;
-       IN1: T2;
+       IN2: T2...;
END_VAR
END_FUNCTION
```
(This should not change the behavior when calling some specific `ADD__...` function with too many arguments because the validation should catch such cases)
=> refactor: Make second parameter in ADD / MUL variadic

src/codegen/generators/statement_generator.rs, src/codegen/tests/debug_tests.rs, src/codegen/tests/debug_tests/snapshots/rusty__codegen__tests__debug_tests__expression_debugging__case_conditions_location_marked.snap
Fixes the debug locations line number, where previously the `switch ...` instruction would have a line number of the last case element.
=> fix: Debug locations of CASE statement

book/src/variables.md
Adds a new section to the `variables.md` section of our book, explaining how and why projects with pointer-initializers need to call the generated `__init___<project name>` function.
=> docs:  add documentation for pointer initializers

.github/workflows/docker.yml
Fix for the workflow, only the x86 image is being built, and thus should be pushed
=> Only push the x86_64 version of the image

.cargo/config.toml
Sometimes running `cargo t --workspace` can result in a lock-up of the machine it is being run on, which is a big problem when working remotely via ssh, since the only way to get your machine back to a working state is a soft-reset. This commit provides a convenient alias to run workspace tests on a single thread.
=> test: add alias to run `cargo t --workspace` on a single thread

libs/stdlib/iec61131-st/to_date_time.st, tests/lit/single/conversion/to_date_time.st
This commit introduces the `TO_TOD` and `TO_LTOD` functions, all making use of already existing `X_TO_Y` functions.
=> feat: Introduce `TO_<DATE,TIME>` functions

src/parser.rs, src/parser/tests/class_parser_tests.rs
Moves the parse-interface logic after the parsing of `EXTENDS` keywords in `parse_pou`.
This allows correct parsing of e.g. `FUNCTION_BLOCK bar EXTENDS foo IMPLEMENTS baz`, registering the implemented interface for the derived function block.
=> fix: parse IMPLEMENTS keyword after EXTENDS

compiler/plc_ast/src/ast.rs, compiler/plc_ast/src/mut_visitor.rs
Cherry-picked changes to `mut_visitor.rs` and `ast.rs` from #1379. 
- the mutating ast-visitor no longer clones nodes when visiting
- `try_from_mut` macro implementation
=> fix: mut_visitor no longer clones

compiler/plc_driver/src/lib.rs, compiler/plc_driver/src/pipelines.rs, compiler/plc_driver/src/pipelines/participant.rs, compiler/plc_driver/src/runner.rs, compiler/plc_driver/src/tests.rs, compiler/plc_source/src/lib.rs, compiler/plc_source/src/source_location.rs
Cherry-picked some changes from the method return branch which are needed to continue with extension development
=> feat: add method to register default participants with pipeline

src/parser.rs, src/parser/tests/container_parser_tests.rs
When looking for action containers, ignore POUs that are not Programs, Functions, Function_Blocks or Classes
=> fix: action containers should not include methods

.vscode/launch.json, src/codegen/debug.rs, src/codegen/generators/pou_generator.rs, src/codegen/tests/debug_tests.rs, src/codegen/tests/debug_tests/snapshots/rusty__codegen__tests__debug_tests__expression_debugging__var_and_vartemp_variables_in_pous_added_as_local.snap, src/index.rs
Make sure temp variables are not part of the program in debug structures.
When adding action debug info, get the struct from the parent pou
fixes #1428
=> fix: correctly handle temp varibles in actions and programs

src/index/tests/index_tests.rs, src/typesystem.rs
Recursive checks were failing in debug if the pou had the same type defined twice
=> fix: recursive type check no longer fails on duplicate fields

src/codegen/tests/function_tests.rs, src/codegen/tests/snapshots/rusty__codegen__tests__function_tests__function_call_with_array_access.snap, src/parser/expressions_parser.rs, src/parser/tests/expressions_parser_tests.rs, src/parser/tests/snapshots/rusty__parser__tests__expressions_parser_tests__function_call_array_index.snap, tests/lit/single/functions/call_with_array_access_on_result.st
This commit allows for code such as `foo()[3];` where `foo` is some POU returning an array
=> fix(parser): Array access on fn-call result

compiler/plc_ast/src/ast.rs, compiler/plc_lowering/src/inheritance.rs, src/index.rs, src/index/indexer.rs, src/index/indexer/pou_indexer.rs, src/index/tests/index_tests.rs, src/index/tests/interface_tests.rs, src/lowering/property.rs, src/lowering/snapshots/rusty__lowering__calls__tests__method_with_string_return_is_changed-2.snap, src/lowering/snapshots/rusty__lowering__calls__tests__method_with_string_return_is_changed.snap, src/parser.rs, src/parser/tests/class_parser_tests.rs, src/parser/tests/interface_parser_tests.rs, src/resolver.rs, src/resolver/tests/resolve_declarations.rs, src/validation.rs, src/validation/global.rs, src/validation/pou.rs, src/validation/recursive.rs, src/validation/tests/interface_validation_tests.rs, src/validation/tests/recursive_validation_tests.rs
Interfaces can now be extended by other interfaces. 
This involves changes in the parsing, indexing, resolving and most importantly the validation stage.
Extends the already existing validations for extended `FUNCTION_BLOCKS` to also take interfaces into account, wherever applicable.
=> feat: extensions in interfaces

compiler/plc_ast/src/ast.rs, compiler/plc_driver/src/cli.rs, compiler/plc_driver/src/pipelines.rs, compiler/plc_lowering/src/inheritance.rs, compiler/plc_xml/src/xml_parser/snapshots/plc_xml__xml_parser__control__tests__jump_and_label_converted_to_ast.snap, compiler/plc_xml/src/xml_parser/snapshots/plc_xml__xml_parser__control__tests__negated_jump_ast.snap, compiler/plc_xml/src/xml_parser/snapshots/plc_xml__xml_parser__control__tests__unconnected_jump_generated_as_empty_statement.snap, compiler/plc_xml/src/xml_parser/snapshots/plc_xml__xml_parser__control__tests__unnamed_controls.snap, src/lowering/property.rs, src/lowering/snapshots/rusty__lowering__calls__tests__function_wirh_array_of_string_return-3.snap, src/lowering/snapshots/rusty__lowering__calls__tests__function_with_string_return_is_changed.snap, src/lowering/snapshots/rusty__lowering__calls__tests__method_with_string_return_is_changed.snap, src/parser/tests/expressions_parser_tests.rs, src/parser/tests/function_parser_tests.rs, src/parser/tests/interface_parser_tests.rs, src/parser/tests/snapshots/rusty__parser__tests__expressions_parser_tests__direct_access_as_expression_parsed.snap, src/parser/tests/snapshots/rusty__parser__tests__expressions_parser_tests__exp_mul_priority_test.snap, src/parser/tests/snapshots/rusty__parser__tests__misc_parser_tests__exponent_literals_parsed_as_variables.snap, src/parser/tests/snapshots/rusty__parser__tests__statement_parser_tests__empty_parameter_assignments_in_call_statement.snap, src/parser/tests/snapshots/rusty__parser__tests__type_parser_tests__typed_inline_enum_with_initial_values_can_be_parsed.snap, src/parser/tests/snapshots/rusty__parser__tests__variable_parser_tests__pou_var_with_address.snap, src/parser/tests/variable_parser_tests.rs, src/tests/adr/initializer_functions_adr.rs
Changes the behavior of the `--ast` flag to always emit the pre-lowered AST while introducing a `--ast-lowered` that matches the current `--ast` output.
Still not perfect in that one can not adjust at what stage to emit the AST (i.e. similar to the participant trait) but good enough for now to peek at the AST before ANY lowering step was executed.
=> cli: Distinguish between pre- and post-lowered AST

.github/workflows/linux.yml, scripts/build.sh, tests/integration/build_description_tests.rs, tests/integration/external_files.rs
There is no need to add the vendor id in our target triples.
This commit removes it from the test but keeps it in the github action for compatiblity.
=> feat: use the target triple without unknown in tests

scripts/build.sh
if using unknown in the target triple, we should make sure the new target variable is set
=> fix: set the rustc_target variable

compiler/plc_ast/src/ast.rs, src/codegen/generators/expression_generator.rs, src/codegen/tests/directaccess_test.rs, src/codegen/tests/parameters_tests.rs, src/index.rs, src/resolver.rs, src/resolver/tests/resolve_expressions_tests.rs, src/tests/adr/annotated_ast_adr.rs, src/validation/pou.rs, tests/integration/build_description_tests.rs, tests/lit/single/functions/segmented_variable_blocks_with_implicit_arguments_call.st
Identical to `StatementAnnotation::Value` with an additional `position` field indicating the position of a parameter in an POU. Helpful for codegen later on when generating the arguments of a function call for implicit calls.
=> refactor: Introduce `StatementAnnotation::Argument`

.vscode/settings.json
This change allows for any std{out,err} output to be displayed in the VSCode terminal when debugging, which by default is disabled. Can be quite useful since the Rust debugger is notoriously bad at displaying the content of complex-ish datastructures.
=> chore: Show output when debugging in VSCode

compiler/plc_driver/src/tests/multi_files.rs, src/codegen/debug.rs, src/codegen/generators/variable_generator.rs, src/codegen/tests/debug_tests.rs, src/codegen/tests/debug_tests/snapshots/rusty__codegen__tests__debug_tests__expression_debugging__external_impl_is_not_added_as_external_subroutine.snap, src/codegen/tests/debug_tests/snapshots/rusty__codegen__tests__debug_tests__expression_debugging__implementation_added_as_subroutine.snap, src/codegen/tests/debug_tests/snapshots/rusty__codegen__tests__debug_tests__expression_debugging__non_function_pous_have_struct_as_param.snap, src/codegen/tests/debug_tests/snapshots/rusty__codegen__tests__debug_tests__expression_debugging__var_and_vartemp_variables_in_pous_added_as_local.snap, src/codegen/tests/initialization_test/complex_initializers.rs, src/codegen/tests/initialization_test/global_initializers.rs, src/codegen/tests/oop_tests.rs, src/codegen/tests/oop_tests/debug_tests.rs, src/codegen/tests/oop_tests/super_tests.rs, src/codegen/tests/snapshots/rusty__codegen__tests__debug_tests__global_var_enum_added_to_debug_info.snap, src/codegen/tests/snapshots/rusty__codegen__tests__debug_tests__global_var_nested_struct_added_to_debug_info.snap, src/codegen/tests/snapshots/rusty__codegen__tests__debug_tests__global_var_struct_added_to_debug_info.snap, src/codegen/tests/snapshots/rusty__codegen__tests__multifile_codegen_tests__datatype_defined_in_external_file_in_module.snap, src/codegen/tests/snapshots/rusty__codegen__tests__multifile_codegen_tests__enum_referenced_in_fb_nested.snap, src/codegen/tests/snapshots/rusty__codegen__tests__multifile_codegen_tests__function_defined_in_external_file.snap, src/codegen/tests/snapshots/rusty__codegen__tests__multifile_codegen_tests__global_value_from_different_file.snap, src/codegen/tests/snapshots/rusty__codegen__tests__multifile_codegen_tests__struct_with_custom_init_in_different_file.snap, src/tests/adr/initializer_functions_adr.rs, tests/integration/snapshots/tests__integration__cfc__ir__conditional_return.snap, tests/integration/snapshots/tests__integration__cfc__ir__conditional_return_evaluating_true.snap, tests/integration/snapshots/tests__integration__cfc__ir__conditional_return_evaluating_true_negated.snap
This PR improves debug info generation for constants by using the `DW_TAG_const_type` debug tag to wrap the types of constants. This enhancement allows external tools to identify constant variables through debug information without breaking existing debugging functionality in addition to correctly conveying which values are constant to the debugger.
The DWARF standard describes two different mechanisms for identifying constants:
> "The `DW_TAG_constant` is used for languages that distinguish between variables that may have constant value and true named constants."
> `DW_TAG_const_type`: "C or C++ const qualified type."
I've chosen `DW_TAG_const_type` as it works well with Inkwell's API and properly represents the semantics of PLC constants (the address is not part of the variables …
=> feat: add proper debug info for constants using DW_TAG_const_type

scripts/build.sh
`build.sh --lit` as well as `build.sh --package` should now work with this PR on MacOS (ARM)
=> fix: build script for macOS development
